# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scheduled Generate
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # check out the source
    - uses: actions/checkout@v3
    # set up python // only corelibs so no reqs required
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # run the update script
    - name: Run DoH Lookup
      run: python3 generate.py
    # commit any changed text files automatically
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        # Commit message
        commit_message: automatic scheduled ip address update
        file_pattern: ./*.txt
