# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scheduled Generate
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    # check out the source
    - uses: actions/checkout@v3
    # set up python // only corelibs so no reqs required
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.3"
        cache: 'pip'
    # install pip dependencies
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"
    # run the update script
    - name: Run DoH Lookup
      run: python3 generate.py
    # commit any changed text files automatically
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        # Commit message
        commit_message: automatic scheduled ip address update
        file_pattern: ./*.txt
